name: Build and deploy NestJS app to Azure Web App - DM--Dummy

typing something here

typed something after backing up to a previous version

Added again after backing up

Adding to line 9

Adding to line 11

Adding to line 14

Adding to line 16

Adding to line 18

Adding to line 20

Adding to line 22

Adding to line 24


