name: Build and deploy NestJS app to Azure Web App - DM--Dummy

typing something here

typed something after backing up to a previous version

Added again after backing up

Adding to line 9

Adding to line 11

Adding to line 13

Adding to line 15

Adding to line 17

Adding to line 19

Adding to line 21

Adding to line 23